


// prevent right click, for display version only
// (function(){
// 	document.addEventListener('contextmenu', function(e){
// 		e.preventDefault();
// 	})
// }());

var contentLinks = document.querySelectorAll('.content-link'),
	closeFocus = document.querySelectorAll('.close-focus'),
	focusContent = document.querySelectorAll('.focus-content'),
	xDown = null,
	delay = 10000,
	// resettingPage = false,
	// timer = [window.setTimeout(cycle, delay)],   // uncomment to activate kiosk style cycling
	randCheck;




// set click handlers for links

for (var i = 0; i < contentLinks.length; i++) {
	contentLinks[i].addEventListener('click', linkRouter);
}

// set click handlers for close buttons on the data points

for (var i = 0; i < closeFocus.length; i++) {
	closeFocus[i].addEventListener('click', close, false);
}

for (var i = 0; i < focusContent.length; i++) {
	focusContent[i].addEventListener('keyup', function(e){
		if(e.key === "Escape" || e.key === "Esc"){
			e.currentTarget.querySelector('.close-focus').click();
		}
	}, false);
}




// when a link is clicked, the linked page is procedurally generated by the following function

function linkRouter(e) {

	// make the background color white. implemented for a cross
	// browser support issue
	document.querySelector('body').className = "schoolPage";


	var 	link = e.currentTarget,
			landing = document.querySelector('#display'),
			content = document.querySelector('#content-page'),
			foci = content.querySelectorAll('.focus'),
			roomName = link.getAttribute('data-content'),
			shade = document.querySelector('.shade'),
			room = rooms[roomName],
			grab = function(element){return content.querySelector(element)};



	// handle the transition from the landing page

	if (link.classList.contains('subject-box')){
		e.preventDefault();
		shade.classList.add('shade-show');
		shade.classList.add(roomName);
		window.setTimeout(fillContent, 200, e);
	} else {
		e.preventDefault();
		fillContent(e);
	};

	// generate a content page

	function fillContent(e){

		// close data point and burger menus, clear background image, open content menu
		resetContent();

		// handle a link back to the landing page
		if (roomName === "school") {
			
			e.preventDefault();

			// switch view to the landing page
			content.style.display = "none";
			content.setAttribute('aria-hidden', 'true');
			landing.style.display = "block";
			landing.setAttribute('aria-hidden', 'false');


			location.hash = "display";

		} else {

			// set background color
			document.querySelector('body').className = roomName;

			// assign bg image, content text, and link destinations
			if (window.matchMedia("(min-width: 768px)").matches || window.matchMedia("(orientation: landscape)").matches){
				grab('.background-image').setAttribute('src', 'assets/' + room.img);
			} else {
				grab('.background-image').setAttribute('src', 'assets/' + room.mobImg);
			}
			grab('.background-image').setAttribute('alt', room.alt);
			grab('#subject-title').innerHTML = room.title;
			grab('#content-info-header').textContent = room.info[0];
			grab('#content-info-text').innerHTML = room.info[1];
			grab('#transition-back').setAttribute('data-content', room.transition[0]);
			grab('#transition-forward').setAttribute('data-content', room.transition[1]);

			// assign text and locations to the data points
			assignFocusPoints();

			// switch view to the content page
			content.style.display = "block";
			content.removeAttribute('aria-hidden');
			landing.style.display = "none";
			landing.setAttribute('aria-hidden', 'true');

			// remove landing to content transition effects, if they exist
			document.querySelector('.shade').className = "shade";


			console.log('hashchange')
			console.log(room)

			document.querySelector('title').innerText = room.pageTitle;
			location.hash = room.hash;
		}
	}

	function assignFocusPoints(){
		for (var i = 0; i < foci.length; i++) {
			var id = "focus" + (i + 1),
				button = document.querySelectorAll('.focus-button')[i];

			focusGrab = function(element){return foci[i].querySelector(element)};
			buttonGrab = function(element){return button.querySelector(element)}

			let arg = foci[i];

			// keep clicks on the dialog box from propagating to the window, which would close the dialog
			foci[i].addEventListener('click',function(e){e.stopPropagation();})


			foci[i].id = id;
			button.id = id + 'button';
			// foci[i].setAttribute('tabindex', i + 2);
			// foci[i].setAttribute('tabindex', 0);

			if (room[id]){

				//clone buttons to remove listeners

				var clone = button.cloneNode(true);
				button.parentElement.replaceChild(clone, button);
				var button = clone;

				pulseOut(button.querySelector('.focus-pulse'));

				// place data points
				if (window.matchMedia("(min-width: 768px)").matches || window.matchMedia("(orientation: landscape)").matches){
					button.style.left = room.locations[i*2];
					button.style.top = room.locations[i*2+1];
					foci[i].style.left = room.locations[i*2];
					foci[i].style.top = room.locations[i*2+1];
				} else {
					button.style.left = room.mobLocations[i*2];
					button.style.top = room.mobLocations[i*2+1];
					foci[i].style.left = room.mobLocations[i*2];
					foci[i].style.top = room.mobLocations[i*2+1];
				}

				button.setAttribute('tabindex', room[id][5]);
				button.querySelector('.aria-description').textContent = room[id][6];
				button.setAttribute('aria-hidden', 'false');

				// add onclick open event
				button.addEventListener('click', openWrapper);

				function openWrapper(e){
					console.log('check');
					e.stopPropagation();
					open(e, arg);
				};
				// button.addEventListener('keypress', function(e){
				// 	if (e.key === 'Enter'){
				// 		open(e, arg);
				// 	}
				// }, false);



				// add focus effects
				button.addEventListener('focus', function(e){
					e.currentTarget.querySelector('.focus-image').setAttribute('src', 'assets/thumbs/PulseButton_FocusState.png');
				}, false);
				button.addEventListener('blur', function(e){
					if (e.currentTarget.querySelector('.focus-image').getAttribute('src') === 'assets/thumbs/PulseButton_FocusState.png'){
						e.currentTarget.querySelector('.focus-image').setAttribute('src', 'assets/thumbs/DataPointNoShadow.png');
					}
				}, false);



				// add text

				focusGrab('.focus-header').innerHTML = room[id][0];
				focusGrab('.p1').innerHTML = room[id][1];
				focusGrab('.p2').innerHTML = room[id][2];
				focusGrab('.p3').innerHTML = room[id][3];
				focusGrab('.close-focus').setAttribute('data-button', button.id)
				// focusGrab('.focus-pulse').textContent = room[id][4];
				// foci[i].textContent = room[id][4];
				// foci[i].insertBefore(document.createTextNode(room[id][4]), foci[i].children[0]);
				buttonGrab('.focus-image').setAttribute('alt', room[id][4]);
				// foci[i].querySelector('.focus-image').setAttribute('alt', room[id][4]);



				foci[i].classList.remove('hidden');
				button.classList.remove('hidden');

			} else {
				foci[i].classList.add('hidden');
				button.classList.add('hidden');
				button.setAttribute('aria-hidden', 'true');
				foci[i].setAttribute('aria-hidden', 'true');
			}
		}
	}

	landing.classList.remove('center');
	content.classList.remove('center');

	window.setTimeout(function(){
		landing.classList.add('center');
		content.classList.add('center');	
	}, 10);


	

}


// close all open elements on content menu, open clicked data point,
// and make it the last child to address stacking context issues

function open(e, arg){
	e.preventDefault();

	var focus = arg,
	 	content = focus.querySelector('.focus-content'),
		parent = focus.parentElement;



	// if open is called on an open data point...
	if (!content.classList.contains("hidden")){
		// close it or ignore it
		if (e.target.classList.contains('focus-button')) {
			content.querySelector('.close-focus').click();
		};
		return;

	}

	e.currentTarget.querySelector('.focus-image').setAttribute('src', 'assets/thumbs/Button_ActiveState.png')

	if (window.matchMedia("(min-width: 768px)").matches || window.matchMedia("(orientation: landscape)").matches){
		closeAll();
	};

	parent.classList.add('front');
		


	content.classList.remove("hidden");
	content.removeAttribute('aria-hidden');

	// handle transition effect
	window.setTimeout(function(){
		content.classList.remove("initial");
	}, 10);

	// stop element from pulsing while open
	e.currentTarget.querySelector('.focus-pulse').classList.add('hidden');
	document.querySelector('#content-page').addEventListener('click', closeAll);

	// content.setAttribute('tabindex','0');
	// content.setAttribute('role', 'dialog');
	
	content.addEventListener('blur',function(e){
		// e.currentTarget.removeAttribute('role');
		// e.currentTarget.removeAttribute('tabindex');
	}, {once: true})

	content.querySelector('.close-focus').focus();



	// content.addEventListener('blur',function(e){
	// 	e.currentTarget.removeAttribute('tabindex');
	// 	// e.currentTarget.querySelector('.close-focus').focus();
	// })

}

// close clicked data point

function close(e){
	e.stopPropagation();
	var content = e.currentTarget.parentElement;
		button = document.querySelector("#" + e.currentTarget.getAttribute('data-button'));

	// button.querySelector('.focus-image').setAttribute('src', "assets/thumbs/DataPointNoShadow.png");
	

	// handle transition effect
	content.classList.add("initial");
	content.setAttribute('aria-hidden', 'true');
	window.setTimeout(function(){
		content.classList.add("hidden");
	}, 400);

	// reset reference display
	content.querySelector('.hide-references').click();
	content.querySelector('.focus-bottom').setAttribute('aria-hidden', 'true');
	
	// resume pulsing
	button.querySelector('.focus-pulse').classList.remove('hidden');
	document.querySelector('#content-page').removeEventListener('click', closeAll);
	document.querySelector('.focus-container').classList.remove('front');



	button.focus();

}

// close all openable elements on the content page

function closeAll(){
	console.log('closing')
	var foci = document.querySelectorAll('.focus-content'),
		expanded = document.querySelectorAll('.expanded'),
		collapsed = document.querySelectorAll('.collapsed');
	
	// close data point boxes
	for (var i = 0; i < foci.length; i++) {
		if (!foci[i].classList.contains('hidden')) {
			foci[i].querySelector('.close-focus').click();
		}
	}

	// close burger and content expandables
	for (var i = 0; i < expanded.length; i++) {
		if (!expanded[i].classList.contains('squished')) {

			expanded[i].classList.add('squished');
			collapsed[i].classList.remove('hidden');
			collapsed[i].removeAttribute('aria-hidden');
			expanded[i].classList.add('hidden');
			expanded[i].setAttribute('aria-hidden', 'true');

		}
	}

	document.querySelector('#content-page').removeEventListener('click', closeAll);
}

// cancel transitions, close everything on the content page, and then open the content info box

function resetContent(){
	var foci = document.querySelectorAll('.focus-content');


	document.querySelector('.background-image').setAttribute('src', '');
	for (var i = 0; i < foci.length; i++) {
		foci[i].classList.add('no-transition');
	};

	closeAll();

	// resettingPage = true;

	document.querySelector('#expand-content-info').click();

	// resettingPage = false;

	for (var i = 0; i < foci.length; i++) {
		foci[i].classList.remove('no-transition');
	};

	document.querySelector('.background-image').focus();
	document.querySelector('.background-image').focus();
	

}

// handle expanding and collapsing relevant elements
function expander(element){
	var expanded = element.querySelector('.expanded'),
		collapsed = element.querySelector('.collapsed'),
		exBtn = element.querySelector('.expand-button'),
		colBtn = element.querySelector('.collapse-button');

	// handle button click to expand element
	exBtn.addEventListener('click', expand);
	exBtn.addEventListener('touchmove', expand);

	// handle button click to collapse element
	colBtn.addEventListener('click', collapse);
	colBtn.addEventListener('touchmove', collapse);

	function expand(e) {
		console.log('expand')

		var button = e.currentTarget;

		e.stopPropagation();
		e.target.blur();
		if (window.matchMedia("(min-width: 768px)").matches || window.matchMedia("(orientation: landscape)").matches){
			closeAll();
		} else {
			document.querySelector('.expanded-content-info').style.top = "";
			document.querySelector('#expand-content-info').style.top = "";
		}

		expanded.classList.remove('hidden');
		expanded.removeAttribute('aria-hidden');

		console.log(button)

		window.setTimeout(function(){
			console.log(button)
			if (button.classList.contains('burger-button')) {
				document.getElementById('burger-menu').style.zIndex = 6;
				document.querySelector('.burger-link').focus();
			};
		}, 200)

		if (button.classList.contains('content-info-button') && (window.matchMedia("(min-width: 768px)").matches || window.matchMedia("(orientation: landscape)").matches)) {
			
			document.querySelector('#content-info-text').setAttribute('tabindex','-1');
			document.querySelector('#content-info-text').focus();

			document.querySelector('#content-info-text').addEventListener('focusout',function(e){
				e.currentTarget.removeAttribute('tabindex');
				document.querySelector('#collapse-content-info').focus();
			}, {once: true})
		}

		window.setTimeout(function(){
			expanded.classList.remove('squished');
		}, 20);
		collapsed.classList.add('hidden');
		collapsed.setAttribute('aria-hidden', 'true');
	};

	function collapse(e) {
		e.stopPropagation();
		e.currentTarget.blur();

		if (window.matchMedia("(max-width: 768px)").matches && window.matchMedia("(orientation: portrait)").matches){
			console.log("calc(95vh - " + window.getComputedStyle(document.querySelector('#content-info-text')).height + ")");
			document.querySelector('.expanded-content-info').style.top = "calc(95vh - " + window.getComputedStyle(document.querySelector('#content-info-text')).height + ")";
			document.querySelector('#expand-content-info').style.top = "calc(95vh - " + window.getComputedStyle(document.querySelector('#content-info-text')).height + ")";
		}

		if (e.currentTarget.classList.contains('burger-button')) {
			document.getElementById('burger-menu').style.zIndex = 2;
			// document.querySelector('burger-link').focus();
		}

		window.setTimeout(function(){
			collapsed.classList.remove('hidden');
			collapsed.removeAttribute('aria-hidden');
		}, 180);
		expanded.classList.add('squished');

		window.setTimeout(function(){
			expanded.classList.add('hidden');
			expanded.setAttribute('aria-hidden', 'true');
		}, 200);

	}
}

// add expandable properties to relevant elements
expander(document.querySelector('#content-info'));
expander(document.querySelector('#burger-menu'));

// handle swiping
function handleTouchStart(e) {                                         
    xDown = e.touches[0].clientX;                                                                     
};                                                

function handleTouchMove(e) {
    if ( !xDown ) {
        return;
    };

    var xUp = e.touches[0].clientX;                                    
    var xDiff = xDown - xUp;

    if ( Math.abs( xDiff ) > 80 ) {/* sensitivity */
        if ( xDiff > 0 && document.querySelector('body').className !== "schoolPage") {
            /* left swipe */
            document.querySelector('#transition-forward').click();
            xDown = null;
        } else if (document.querySelector('body').className !== "schoolPage"){
            /* right swipe */
            document.querySelector('#transition-back').click();
            xDown = null;
        }                       
    }

};

function handleTouchEnd(e) {
	xDown = null;
};

// assign event listeners for swiping
document.addEventListener('touchstart', handleTouchStart, false);        
document.addEventListener('touchmove', handleTouchMove, false);
document.addEventListener('touchend', handleTouchEnd, false);


// pulse the data points
function pulseOut(el, check) {
	el.classList.add('pulse-out');
	window.setTimeout(pulseMiddle, 2000, el, check);
}

function pulseMiddle(el, check) {
	el.classList.remove('pulse-out');
	el.classList.add('pulse-in');
	window.setTimeout(pulseIn, 2000, el, check);
}

function pulseIn(el, check) {
	el.classList.remove('pulse-in');
	if (!check) {
		pulseOut(el);
	};
}

for (var i = 0; i < document.querySelectorAll('.focus-pulse').length; i++) {
	pulseOut(document.querySelectorAll('.focus-pulse')[i]);
}

pulseOut(document.querySelector('.subject-box-pulse'));


// pulse the content boxes
function pulseRandom(){

	boxes = document.querySelectorAll('.content-link .subject-box-pulse');
	shrink = function(el){ el.classList.remove('pulse-out') };
	grow = function(el){ el.classList.add('pulse-out') };
	int = Math.floor(Math.random() * 6);

	
	while (int === randCheck) {
		int = Math.floor(Math.random() * 6);
	}

	randCheck = int;

	pulseOut(boxes[int], true);

	window.setTimeout(pulseRandom, 2000);
}

pulseRandom();


// add a bounce to page transitions

function overshoot(e) {
	e.preventDefault();

	classList = document.querySelector('#content-page').classList;
	next = e.currentTarget.getAttribute('data-content');

	if (next === "school"){
    	document.querySelector('.home').click();
    	return;
	}

	document.querySelector('body').className = next;
    
	bounce = function(dir){
    	classList.add(dir);
    	window.setTimeout(function(){
    		classList.add('no-transition');
    		classList.remove(dir);
    		document.querySelectorAll('.' + next)[2].click();
    		classList.add(dir === "right" ? "left" : "right");

    		window.setTimeout(function(){
    			classList.remove('no-transition');
   				classList.remove(dir == "right" ? "left" : "right");
    		}, 10);

    	}, 200);
    }


    if (e.currentTarget.id === "transition-forward"){
    	bounce("right");
    } else {
    	bounce("left");
    }
}

for (var i = 0; i < document.querySelectorAll('.transition').length; i++) {
	document.querySelectorAll('.transition')[i].addEventListener('click', overshoot);
	document.querySelectorAll('.transition')[i].addEventListener('focus', function(e){
		e.currentTarget.querySelector('.chevron-image').setAttribute('src', 
			e.currentTarget.querySelector('.chevron-image').getAttribute('src').split('.')[0] + "-focus" + ".svg");
	});
	document.querySelectorAll('.transition')[i].addEventListener('blur', function(e){
		e.currentTarget.querySelector('.chevron-image').setAttribute('src', 
			e.currentTarget.querySelector('.chevron-image').getAttribute('src').slice(0,17) + ".svg");
	});

}


// document.querySelector('body').addEventListener('mousemove', resetCycle);

// document.querySelector('body').addEventListener('click', resetCycle);

// document.querySelector('body').addEventListener('keypress', resetCycle);

// document.querySelector('body').addEventListener('touchmove', resetCycle);


function resetCycle() {
	for (var i = 0; i < timer.length; i++) {
		window.clearTimeout(timer[i]);
	};

	timer = [];
	timer[0] = window.setTimeout(cycle, delay);
}


function cycle() {

	var body = document.querySelector('body');

	if (body.className === "" || body.className === "schoolPage") {
		console.log("landing");
		body.querySelector('.subject-box.math').click();
	} else {
		var foci = body.querySelectorAll('.focus');
		focusTimer(0, delay);
		focusTimer(1, delay);

		if (body.className !== "math"){
			focusTimer(2, delay);
			timer[4] = window.setTimeout(function(){
				body.querySelector('#transition-forward').click();
			}, delay * 3)
		} else {
			timer[4] = window.setTimeout(function(){
				body.querySelector('#transition-forward').click();
			}, delay * 2)
		}

		console.log(body.className);
	}

	function focusTimer(i, duration){
		window.clearTimeout(timer[i+1]);
		timer[i+1] = window.setTimeout(function(){
			foci[i].click();
		}, (duration * i));
	};

}


// function revealReference(e) {
// 	var text = e.currentTarget.parentElement.parentElement,
// 		content = text.parentElement;
// 		fixed = window.getComputedStyle(content).height;
// 	content.style.height = fixed;
// 	text.querySelector('.focus-bottom').style.display = "block";
// 	text.querySelector('.focus-bottom').style.marginTop = fixed;
// 	text.style.top = "calc((" + fixed + " * -1.6)";

// }

// function hideReference(e) {
// 	var text = e.currentTarget.parentElement.parentElement,
// 		content = text.parentElement;
// 		fixed = window.getComputedStyle(content).height;
// 	text.style.top = "";
// 	window.setTimeout(function(){
// 		content.style.height = "";
// 		text.querySelector('.focus-bottom').style.marginTop = "";
// 		text.querySelector('.focus-bottom').style.display = "";
// 	}, 500)
// }

function revealReference(e) {
	var text = e.currentTarget.parentElement.parentElement,
		content = text.parentElement;

	content.style.overflow = "display";
	text.querySelector('.focus-bottom').style.display = "block";
	text.querySelector('.focus-bottom').setAttribute('aria-hidden', 'false');
	// text.querySelector('.focus-bottom').setAttribute('aria-expanded', 'true');
	window.setTimeout(function(){
		text.querySelector('.focus-bottom').focus();	
	}, 10);
	e.currentTarget.style.display = "none";
	e.currentTarget.setAttribute('aria-hidden', 'true');
}

function hideReference(e) {
	var text = e.currentTarget.parentElement.parentElement,
		content = text.parentElement;
		fixed = window.getComputedStyle(content).height;
	
	content.style.overflow = "";
	content.querySelector('.show-references').style.display = "";
	content.querySelector('.show-references').setAttribute('aria-hidden', 'false');
	// window.setTimeout(function(){
	text.querySelector('.focus-bottom').style.display = "";
	text.querySelector('.focus-bottom').setAttribute('aria-hidden', 'true');
	// text.querySelector('.focus-bottom').setAttribute('aria-expanded', 'false');

	content.querySelector('.show-references').focus();

	// }, 500)
}

for (var i = 0; i < document.querySelectorAll('.show-references').length; i++) {
	document.querySelectorAll('.show-references')[i].addEventListener('click', revealReference);
}

for (var i = 0; i < document.querySelectorAll('.hide-references').length; i++) {
	document.querySelectorAll('.hide-references')[i].addEventListener('click', hideReference);
}







// document.querySelector('.exit-content').addEventListener('click', function(){
//     	document.querySelector('.home').click();
// });



// keep reload from navigating to the bare #content-page
(function(){
	// location.hash = "display";
	// switch (location.hash) {
	// 	case ""
	// }
	function router() {

		switch (location.hash) {
			case "#preparation":
				//document.querySelector('.burger-link.office').click();
				//break;
			case "#technology":
				document.querySelector('.burger-link.math').click();
				break;
			case "#standards":
				document.querySelector('.burger-link.english').click();
				break;
			case "#management":
				document.querySelector('.burger-link.science').click();
				break;
			case "#characteristics":
				document.querySelector('.burger-link.social').click();
				break;
			case "#supports":
				document.querySelector('.burger-link.teachers').click();
				break;
			default:
				document.querySelector('.burger-link.home').click();
				document.querySelector('title').innerText = "Westat - Supporting Educators";
				break;
		}
	}

	// window.setTimeout(router, 10);
	router();
	window.onhashchange = function(e){
		router();
	}
}());


// document.addEventListener('focusin', function(e){
// 	// e.target.setAttribute('role', 'alert');
// 	// e.target.setAttribute('aria-live','assertive');
// 	if (e.target.querySelector('.alert')){
// 		e.target.querySelector('.alert').setAttribute('aria-hidden', false);
// 	}
// })
// document.addEventListener('focusout',function(e){
// 	// e.target.removeAttribute('role');
// 	// e.target.removeAttribute('aria-live');
// 	if (e.target.querySelector('.alert')){

// 		e.target.querySelector('.alert').setAttribute('aria-hidden', true);
// 	}

// })

